BBBB BBBBBBBB BBBBBBBBBBBB
XXXXXX
    XXXXXX
        XXXXXXXBBBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXX
        BBBBBBBBBBBB BBBBB
    XXXXXXX
    XXXXXX
        BBBBBBBBBBB
        BBBBBBBBBBB BBBBBBBBB
        BBBBBBBBBBBB BBBB
    XXXXXXX
XXXXXXX
